"""Render paper/macros.tex from outputs/session28/numbers.json (master plan A5/D1).

One \\providecommand per macro-bound number, e.g.

    \\providecommand{\\NumReprWakeJEPA}{0.71}
    \\providecommand{\\CIReprWakeJEPAlo}{0.58}

Formatting: each record's optional "fmt" (printf-style) controls rendering;
default %.2f. Records with ci_lo/ci_hi additionally emit <Macro>lo / <Macro>hi.
Phase D replaces every hand-typed number in the .tex with these macros; the D1
audit greps the sections for residual numeric literals.

Usage:
    python scripts/session28/emit_macros.py \
        [--numbers outputs/session28/numbers.json] [--out paper/macros.tex]
"""

from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]


def fmt_value(value, fmt: str) -> str:
    if fmt == "%s":
        return str(value)
    return fmt % value


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--numbers", default="outputs/session28/numbers.json")
    p.add_argument("--out", default="paper/macros.tex")
    args = p.parse_args()

    blob = json.loads((REPO / args.numbers).read_text())
    numbers = blob["numbers"]
    prov = blob.get("_provenance", {})

    lines = [
        "% AUTO-GENERATED by scripts/session28/emit_macros.py. DO NOT EDIT.",
        f"% source: {args.numbers}",
        f"% generated: {datetime.now(timezone.utc).isoformat()}",
        f"% numbers.json provenance commit: {prov.get('git_commit', 'UNKNOWN')}",
        f"% protocol sha256: {prov.get('protocol_sha256', 'UNKNOWN')}",
    ]
    n_macros = 0
    for name in sorted(numbers):
        rec = numbers[name]
        macro = rec.get("macro")
        if not macro:
            continue
        fmt = rec.get("fmt", "%.2f")
        lines.append(f"\\providecommand{{\\{macro}}}{{{fmt_value(rec['value'], fmt)}}}")
        n_macros += 1
        for suffix, key in (("lo", "ci_lo"), ("hi", "ci_hi")):
            if key in rec:
                lines.append(
                    f"\\providecommand{{\\{macro}{suffix}}}{{{fmt_value(rec[key], fmt)}}}"
                )
                n_macros += 1

    out = REPO / args.out
    out.write_text("\n".join(lines) + "\n")
    print(f"[emit_macros] {n_macros} macros -> {out}")


if __name__ == "__main__":
    main()
