#!/usr/bin/env bash
# Rasterize the paper's figure PDFs into trimmed PNGs for the talk deck.
# Run from anywhere; writes to paper/talk/figs/. Requires pdftocairo + ImageMagick.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SRC="$REPO/paper/sections/figures"
OUT="$REPO/paper/talk/figs"
mkdir -p "$OUT"

conv() {  # <src-rel-to-SRC> <dst-name>
  local src="$SRC/$1" dst="$2"
  [ -f "$src" ] || { echo "MISSING: $src"; return; }
  case "$src" in
    *.pdf) pdftocairo -png -singlefile -r 200 "$src" "$OUT/$dst" ;;
    *.png) cp "$src" "$OUT/$dst.png" ;;
  esac
  convert "$OUT/$dst.png" -trim +repage -bordercolor white -border 14 "$OUT/$dst.png"
  echo "ok: $dst"
}

# main deck
conv tikz/fig1_jepa_architecture.pdf            jepa_architecture
conv tikz/fig2_predictive_vs_reconstructive.pdf predict_vs_reconstruct
conv tikz/fig_eval_protocol.pdf                 eval_protocol
conv tikz/fig4_b1_fairness.pdf                  controls_fairness
conv results/graphical_abstract.pdf             graphical_abstract
conv results/fig_scale_decomp.pdf               scale_decomp
conv results/fig4_closure.pdf                   closure
conv results/fig_wake_code.pdf                  wake_code
conv results/fig_horizon_sweep.pdf              horizon_sweep
conv results/figC_cycle.pdf                     cycle
conv results/fig_ot.pdf                         ot
conv results/figG_flow_recovery.pdf             flow_recovery
conv results/figB_paramspace.pdf                paramspace
conv results/figC_pressure_observability.png    pressure_observability
# backups
conv tikz/fig3_predictor_detail.pdf             predictor_detail
conv results/figD_reconstructions.pdf           reconstructions
conv results/figE_sensor_placement.pdf          sensor_placement
conv results/fig5_b1_results.pdf                b1_results_full
conv results/figS_recon_test_b.pdf              recon_test_b
conv results/fig_persistence.pdf                persistence
conv results/fig_phase_amplitude.pdf            phase_amplitude

# slide-16 custom figure is generated by make_fig_cl_inference.py (no external data)
echo "Now run: python make_fig_cl_inference.py  (slide-16 figure)"
