"""Render the DNS metadata table (Table 1) from paper/dns_metadata.yaml (SESSION29.8 S0).

The LaTeX table is generated from the YAML single source of truth, never
hand-edited. A null value renders as the \\pending{} marker; a filled value
renders verbatim. Output: paper/sections/tables/table_dns_metadata.tex, which
the manuscript \\input{}s.

Usage:
    python scripts/session29/render_table1_from_yaml.py
"""

from __future__ import annotations

from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[2]
YAML = REPO / "paper" / "dns_metadata.yaml"
OUT = REPO / "paper" / "sections" / "tables" / "table_dns_metadata.tex"


def cell(value) -> str:
    """A filled value renders verbatim; null renders as the pending marker."""
    if value is None or str(value).strip() == "":
        return "\\pending{}"
    return str(value)


def main() -> None:
    meta = yaml.safe_load(YAML.read_text())
    rows = meta["rows"]
    n_pending = sum(1 for r in rows if r.get("value") in (None, ""))
    body = []
    for r in rows:
        body.append(f"    {r['quantity']} & {cell(r.get('value'))} & {r['why']} \\\\")
    lines = [
        "% AUTO-GENERATED by scripts/session29/render_table1_from_yaml.py from",
        "% paper/dns_metadata.yaml. DO NOT EDIT; edit the YAML and re-render.",
        f"% pending rows: {n_pending} of {len(rows)}",
        "\\begin{table}",
        "  \\centering",
        "  {\\small",
        "  \\fittab{\\begin{tabular}{@{}p{0.29\\textwidth}l p{0.43\\textwidth}@{}}",
        "    \\toprule",
        "    Quantity & Value & Why a referee needs it \\\\",
        "    \\midrule",
        *body,
        "    \\bottomrule",
        "  \\end{tabular}}}",
        "  \\caption{DNS solver-resolution details required for full reproducibility",
        "  (\\S\\ref{sec:flow_observables}). The data are direct numerical simulations",
        "  with no subgrid-scale model, so all scales are resolved and no large-eddy",
        "  closure is involved. Values marked pending are owned by the simulation",
        "  collaborators and are filled from \\texttt{paper/dns\\_metadata.yaml} before",
        "  submission.}",
        "  \\label{tab:dns_pending}",
        "\\end{table}",
    ]
    OUT.write_text("\n".join(lines) + "\n")
    print(f"[render_table1] {len(rows)} rows ({n_pending} pending) -> {OUT}")


if __name__ == "__main__":
    main()
