"""All-JEPA closure comparison table (d=4,8,16,32,64 + no-lift d=64).

Combines the canonical dimsweep CSV (d16/32/64) with the d-sweep CSV (d8/d4/no-lift)
produced by closure_r2_dsweep.py. Both come from the SAME exp_closure_r2 probe, so
rows are directly comparable. Reports, at H=16 on test_b:
  - representational wake-enstrophy MAE (z_dns, the headline metric)
  - forecast R^2 (z_markov) for C_L, wake-enstrophy, and the 6-observable mean.
Emits a LaTeX table and a plain-text summary.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

REPO = Path(__file__).resolve().parents[2]
DIMSWEEP = REPO / "outputs/session23_closure/closure_r2_dimsweep_d16.csv"
DSWEEP = REPO / "outputs/session23_closure/closure_r2_dsweep.csv"
DSWEEP_NOC = REPO / "outputs/session23_closure/closure_r2_noc.csv"
OUT_TEX = REPO / "paper/sections/tables/jepa_dimsweep_table.tex"

METRICS = ["C_L", "C_D", "I_y", "wake_enstrophy", "circulation_pos", "circulation_neg"]
# tag -> (label, d, configuration description, sort key)
VARIANTS = [
    ("jepa_d64_test1_noBN",   "64",  64, "lift $+$ wake", 0),
    ("jepa_d32_noBN",         "32",  32, "lift $+$ wake", 1),
    ("jepa_d16_noBN",         "16",  16, "lift $+$ wake", 2),
    ("jepa_d8_noBN",          "8",    8, "lift $+$ wake", 3),
    ("jepa_d4_noBN",          "4",    4, "lift $+$ wake", 4),
    ("jepa_d64_nolift_noBN",  "64",  64, "wake only",     5),
    ("jepa_d64_noc_noBN",     "64",  64, r"lift $+$ wake, no $\cvec$", 6),
]


def load() -> pd.DataFrame:
    frames = []
    for p in (DIMSWEEP, DSWEEP, DSWEEP_NOC):
        if p.exists():
            frames.append(pd.read_csv(p))
        else:
            print(f"[build_jepa_table] NOTE: {p.name} absent (run closure first)")
    df = pd.concat(frames, ignore_index=True)
    return df[(df.kind == "jepa") & (df.split == "test_b") & (df.horizon == 16)]


def report_noc(df) -> None:
    """Print the no-conditioning ablation: c-conditioned d=64 vs no-c d=64."""
    noc_tag = "jepa_d64_noc_noBN"
    if noc_tag not in set(df.baseline):
        print("\n[no-c] closure_r2_noc.csv absent or empty (run closure_noc.sh)")
        return
    print("\n=== no-conditioning ablation (d=64, lift+wake, only the predictor c differs) ===")
    print(f"{'config':22s} {'wakeMAE':>8s} {'CL_R2':>7s} {'wake_R2':>8s} {'mean_R2':>8s}")
    for tag, name in [("jepa_d64_test1_noBN", "with (G,D,Y) cond"),
                      (noc_tag, "no (G,D,Y) cond")]:
        wmae = val(df, tag, "z_dns", "wake_enstrophy", "mae")
        clr = val(df, tag, "z_markov", "C_L", "r2")
        wkr = val(df, tag, "z_markov", "wake_enstrophy", "r2")
        mnr = np.nanmean([val(df, tag, "z_markov", m, "r2") for m in METRICS])
        print(f"{name:22s} {wmae:8.2f} {clr:7.3f} {wkr:8.3f} {mnr:8.3f}")


def val(df, tag, mode, metric, col):
    r = df[(df.baseline == tag) & (df["mode"] == mode) & (df.metric == metric)]
    return float(r[col].iloc[0]) if len(r) else np.nan


def main() -> None:
    df = load()
    rows = []
    for tag, label, d, aux, _ in VARIANTS:
        wake_mae = val(df, tag, "z_dns", "wake_enstrophy", "mae")
        cl_r2 = val(df, tag, "z_markov", "C_L", "r2")
        wake_r2 = val(df, tag, "z_markov", "wake_enstrophy", "r2")
        mean_r2 = np.nanmean([val(df, tag, "z_markov", m, "r2") for m in METRICS])
        rows.append((label, d, aux, wake_mae, cl_r2, wake_r2, mean_r2))

    print(f"\n{'variant':16s} {'wakeMAE':>8s} {'CL_R2':>7s} {'wake_R2':>8s} {'mean_R2':>8s}")
    for label, d, aux, wmae, clr, wkr, mnr in rows:
        tag = f"d={label} {aux.replace('$+$','+')}"
        print(f"{tag:16s} {wmae:8.2f} {clr:7.3f} {wkr:8.3f} {mnr:8.3f}")

    # LaTeX
    body = []
    for label, d, aux, wmae, clr, wkr, mnr in rows:
        def f(x, p): return "---" if np.isnan(x) else f"{x:.{p}f}"
        body.append(f"    {label} & {aux} & {f(wmae,2)} & {f(clr,3)} & {f(wkr,3)} & {f(mnr,3)} \\\\")
    tex = r"""% Auto-generated by scripts/session23/build_jepa_table.py. Do not edit by hand.
\begin{table}[t]
  \centering
  \caption{Latent-dimension sweep and the two head/conditioning ablations for the
  predictive (JEPA) family, at $H = 16$ on the $n = 42$ test\_b encounters, under
  the matched predictor and probes of \S\ref{sec:res_controls}. ``Repr.\ wake MAE''
  is the representational mean absolute error of the wake enstrophy from the
  simulation-encoded latent (smaller is better); the $R^2$ columns are the forecast
  coefficient of determination of the Markov rollout (larger is better, the
  predict-the-mean floor is $0$); ``mean $R^2$'' averages the six observables. The
  ``wake only'' row removes the instantaneous-lift head at matched $d = 64$ (the
  complement of the wake-removal control in Table~\ref{tab:controls_2x2}); the
  ``no $\cvec$'' row instead removes the gust-parameter conditioning from the
  predictor at matched $d = 64$, so the model never sees $(G,D,Y)$.}
  \label{tab:jepa_dimsweep}
  \small
  \begin{tabular}{l l c c c c}
    \toprule
    $d$ & Configuration & Repr.\ wake MAE & $C_L$ $R^2$ & wake $R^2$ & mean $R^2$ \\
    \midrule
""" + "\n".join(body) + r"""
    \bottomrule
  \end{tabular}
\end{table}
"""
    OUT_TEX.parent.mkdir(parents=True, exist_ok=True)
    OUT_TEX.write_text(tex)
    print(f"\n[build_jepa_table] wrote {OUT_TEX.relative_to(REPO)}")

    report_noc(df)


if __name__ == "__main__":
    main()
