"""Diameter-controlled return-to-baseline sweep, v2.1 unconditioned rebuild.

Identical analysis to orbit_return_controlled.py (hold core diameter D and
sign(G) fixed, average distance-to-orbit over each case's encounters, vary only
|G|), but on the v2.1 canonical predictive latent (jepa_tf_noc_d64_s42) and the
v2.1 split. Applies the paper figure style and dumps the peak/end distances and
the orbit band to JSON so the appendix prose can be macro-wired.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402
from scipy.spatial.distance import cdist  # noqa: E402

REPO = Path("/home/carlos/GUST-JEPA")
sys.path.insert(0, str(REPO / "scripts" / "session21"))
import figstyle as fs  # noqa: E402
LAT = REPO / "outputs/session28/latents/jepa_tf_noc_d64_s42"
OUT_PDF = REPO / "paper/sections/figures/results/appA_orbit_return_v2p1.pdf"
OUT_PNG = REPO / "outputs/session28/drift/appA_orbit_return_v2p1.png"
OUT_JSON = REPO / "outputs/session28/drift/orbit_return_v2p1.json"
PART = REPO / "outputs/session28/numbers_parts/orbit_return.json"
IMPACT = 40
RELEASE = 79  # window end relative to impact (120-frame encounter, impact at 40)


def main() -> None:
    fs.use_style()
    tr = np.load(LAT / "train.npz", allow_pickle=True)
    G, D, Y = tr["G"], tr["D"], tr["Y"]
    zf = tr["z_full"]
    base = zf[np.isclose(G, 0.0)].reshape(-1, 64)
    mu = base.mean(0)
    diam = np.linalg.norm(base - mu, axis=1).max() * 2.0
    dd = cdist(base, base)
    np.fill_diagonal(dd, np.inf)
    band = float(np.percentile(dd.min(1), 95) / diam)

    Dfix = 1.0
    levels = [-0.5, -1.0, -1.5, -2.0, -3.0]
    cand_Y = sorted(set(np.round(Y[(np.isclose(D, Dfix)) & (G < 0)], 2)))
    bestY, bestn = None, -1
    for yv in cand_Y:
        n = sum(((np.isclose(G, g)) & np.isclose(D, Dfix) & np.isclose(Y, yv)).any()
                for g in levels)
        if n > bestn:
            bestY, bestn = yv, n
    print(f"diam={diam:.3f} band={band:.3f}  fixed D={Dfix}, Y={bestY} "
          f"(covers {bestn}/{len(levels)} |G|)")

    trel = np.arange(120) - IMPACT
    fig, ax = plt.subplots(figsize=fs.figure_size(0.82, aspect=0.52))
    ax.axhspan(0, band, color="0.88", label="orbit thickness")
    cmap = plt.cm.viridis(np.linspace(0.15, 0.9, len(levels)))
    rows = []
    for c, g in zip(cmap, levels):
        m = np.isclose(G, g) & np.isclose(D, Dfix) & np.isclose(Y, bestY)
        ytag = ""
        if m.sum() == 0:
            sub = np.where(np.isclose(G, g) & np.isclose(D, Dfix))[0]
            if len(sub) == 0:
                continue
            yv = Y[sub][np.argmin(np.abs(Y[sub] - bestY))]
            m = np.isclose(G, g) & np.isclose(D, Dfix) & np.isclose(Y, yv)
            ytag = f"$Y={yv:+.2f}$"
        curves = np.stack([cdist(zf[j], base).min(1) / diam for j in np.where(m)[0]])
        mean = curves.mean(0)
        ax.plot(trel, mean, color=c, lw=1.5, label=f"$G={g:+.1f}$ {ytag}".strip())
        rows.append(dict(G=float(g), n_enc=int(m.sum()), d_max=float(mean.max()),
                         d_end=float(mean[-1]), slope_end=float(mean[-1] - mean[-6])))
        print(f"  G={g:+.1f} D={Dfix} {ytag or f'Y={bestY:+.2f}'}: n_enc={m.sum()} "
              f"d@max={mean.max():.2f} d@end={mean[-1]:.2f} slope@end={mean[-1]-mean[-6]:+.2f}")
    ax.axvline(0, color="k", lw=0.6, ls=":")
    ax.axvline(RELEASE, color="0.5", lw=0.6, ls="--")
    ax.set_xlabel(f"frames relative to impact (window ends at $+{RELEASE}$)")
    ax.set_ylabel("distance to orbit (/ diameter)")
    ax.legend(fontsize=7, ncol=2, loc="upper right")
    ax.set_xlim(-40, RELEASE)
    fig.tight_layout()
    OUT_PDF.parent.mkdir(parents=True, exist_ok=True)
    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(OUT_PDF)
    fig.savefig(OUT_PNG, dpi=160)

    d_max = [r["d_max"] for r in rows]
    summary = dict(diam=diam, band=band, Dfix=Dfix, bestY=float(bestY),
                   release=RELEASE, levels=[r["G"] for r in rows],
                   d_max_min=min(d_max), d_max_max=max(d_max),
                   all_contracting=bool(all(r["slope_end"] < 0 for r in rows)),
                   strongest_ends_closest=bool(
                       rows[-1]["d_end"] == min(r["d_end"] for r in rows)),
                   rows=rows)
    json.dump(summary, open(OUT_JSON, "w"), indent=1)

    # eval_all numbers part (macro-bound peak-distance range for the appendix prose)
    note_min = ("diameter-controlled |G| sweep at fixed D=1.0, G<0, v2.1 "
                "jepa_tf_noc_d64_s42 latent; min over |G| in [0.5,3.0] of the "
                "per-case mean peak distance to the no-gust orbit, in orbit "
                "diameters; appendix orbit-return figure; generated by "
                "scripts/session23/orbit_return_controlled_v2p1.py")
    note_max = ("max over |G| in [0.5,3.0] of the per-case mean peak distance to "
                "the no-gust orbit, in orbit diameters; companion to "
                "orbit_return_peak_min; all five strengths still contracting at the "
                "window end and the strongest ends closest")
    part = {"part": "orbit_return", "numbers": {
        "orbit_return_peak_min": {
            "macro": "OrbitReturnPeakMin", "value": summary["d_max_min"],
            "fmt": "%.1f", "split": "train",
            "observable": "distance_to_baseline_orbit", "note": note_min},
        "orbit_return_peak_max": {
            "macro": "OrbitReturnPeakMax", "value": summary["d_max_max"],
            "fmt": "%.1f", "split": "train",
            "observable": "distance_to_baseline_orbit", "note": note_max}}}
    PART.parent.mkdir(parents=True, exist_ok=True)
    json.dump(part, open(PART, "w"), indent=1)
    print(f"wrote {OUT_PDF}\nwrote {OUT_JSON}\nwrote {PART}")
    print("SUMMARY:", json.dumps({k: summary[k] for k in
          ("d_max_min", "d_max_max", "all_contracting",
           "strongest_ends_closest", "band")}, indent=0))


if __name__ == "__main__":
    main()
