"""Render paper/macros_v3.tex from outputs/session33/numbers.json.

Identical rendering to scripts/session28/emit_macros.py (one \\providecommand
per macro-bound record, optional <Macro>lo / <Macro>hi from ci_lo/ci_hi,
printf-style "fmt", default %.2f). Collision safety against the v2.1
macros.tex lives in eval_all_v3.py, which must be run first.

Usage:
    python -m scripts.session33.emit_macros_v3 \
        [--numbers outputs/session33/numbers.json] [--out paper/macros_v3.tex]
"""

from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]


def fmt_value(value, fmt: str) -> str:
    if fmt == "%s":
        return str(value)
    return fmt % value


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--numbers", default="outputs/session33/numbers.json")
    p.add_argument("--out", default="paper/macros_v3.tex")
    args = p.parse_args()

    blob = json.loads((REPO / args.numbers).read_text())
    numbers = blob["numbers"]
    prov = blob.get("_provenance", {})

    lines = [
        "% AUTO-GENERATED by scripts/session33/emit_macros_v3.py. DO NOT EDIT.",
        f"% source: {args.numbers}",
        f"% generated: {datetime.now(timezone.utc).isoformat()}",
        f"% numbers.json provenance commit: {prov.get('git_commit', 'UNKNOWN')}",
    ]
    n_macros = 0
    for name in sorted(numbers):
        rec = numbers[name]
        macro = rec.get("macro")
        if not macro:
            continue
        fmt = rec.get("fmt", "%.2f")
        lines.append(f"\\providecommand{{\\{macro}}}{{{fmt_value(rec['value'], fmt)}}}")
        n_macros += 1
        for suffix, key in (("lo", "ci_lo"), ("hi", "ci_hi")):
            if key in rec:
                lines.append(
                    f"\\providecommand{{\\{macro}{suffix}}}{{{fmt_value(rec[key], fmt)}}}"
                )
                n_macros += 1

    out = REPO / args.out
    out.write_text("\n".join(lines) + "\n")
    print(f"[emit_macros_v3] {n_macros} macros -> {out}")


if __name__ == "__main__":
    main()
