"""Render the Session 31 loss-kit on/off matrix for review (Track A gate A).

Loads every model config under one or more directories, validates each against
the four fail-loud rules, and writes a markdown table whose columns are exactly
the kit switches: recon, pred, anti_collapse (with method), lift, wake. The
table is grouped by source directory so canonical, reference and ablation
configs render together.

Usage::

    python -m src.config.audit --configs configs/canonical/ \\
        --out outputs/session31/config_audit.md
    python -m src.config.audit --configs configs/canonical configs/reference \\
        configs/ablation --out outputs/session31/config_audit.md
"""

from __future__ import annotations

import argparse
from pathlib import Path

from src.config.kit_config import KitConfigError, load_model_config

# bvae uses a native MSE+KL objective the kit cannot express; its wake column is
# pending Carlos. Flag it in the matrix rather than presenting it as kit-faithful.
_PENDING_MODELS = {"bvae"}

_COLUMNS = ["Model", "recon", "pred", "anti_collapse", "lift", "wake", "encoder/latent", "notes"]


def _onoff(flag: bool) -> str:
    return "on" if flag else "off"


def audit_dir(directory: Path) -> list[dict[str, str]]:
    """Validate every ``*.yaml`` (except ``_kit.yaml``) in ``directory``.

    Returns a list of rendered-cell dicts, one per config, sorted by filename.
    A config that fails validation is rendered as an ``ERROR`` row rather than
    aborting the whole audit.
    """
    rows: list[dict[str, str]] = []
    for path in sorted(directory.glob("*.yaml")):
        if path.name == "_kit.yaml":
            continue
        try:
            cfg = load_model_config(path)
        except (KitConfigError, FileNotFoundError) as exc:
            rows.append(
                {
                    "Model": path.stem,
                    "recon": "?",
                    "pred": "?",
                    "anti_collapse": "?",
                    "lift": "?",
                    "wake": "?",
                    "encoder/latent": "?",
                    "notes": f"ERROR: {exc}",
                    "_ok": "false",
                }
            )
            continue

        ro = cfg.representation_objective
        ac = cfg.anti_collapse
        sup = cfg.supervision
        pending = cfg.name in _PENDING_MODELS
        notes = []
        if pending:
            notes.append("PENDING (native MSE+KL; wake TBC)")
        if cfg.model.get("encoder", "").endswith("_native"):
            notes.append("own arch")

        rows.append(
            {
                "Model": cfg.name,
                "recon": _onoff(ro["recon"]["on"]),
                "pred": _onoff(ro["pred"]["on"]),
                "anti_collapse": ac["method"] if ac["on"] else "off",
                "lift": _onoff(sup["lift_head"]["on"]),
                "wake": "TBC" if pending else _onoff(sup["wake_head"]["on"]),
                "encoder/latent": f"{cfg.model.get('encoder', '-')}/{cfg.model.get('latent', '-')}",
                "notes": "; ".join(notes),
                "_ok": "true",
            }
        )
    return rows


def render_markdown(grouped: dict[str, list[dict[str, str]]]) -> str:
    """Render grouped audit rows as a markdown document."""
    lines = ["# Session 31 loss-kit config audit", ""]
    lines.append(
        "On/off matrix of every model config. Columns are the kit switches; "
        "`anti_collapse` shows the method when on. Generated by "
        "`python -m src.config.audit`; do not hand-edit."
    )
    lines.append("")
    header = "| " + " | ".join(_COLUMNS) + " |"
    sep = "| " + " | ".join(["---"] * len(_COLUMNS)) + " |"
    for group, rows in grouped.items():
        lines.append(f"## {group}")
        lines.append("")
        lines.append(header)
        lines.append(sep)
        for r in rows:
            lines.append("| " + " | ".join(r.get(c, "") for c in _COLUMNS) + " |")
        lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--configs",
        nargs="+",
        required=True,
        help="One or more directories of per-model YAML configs.",
    )
    parser.add_argument(
        "--out",
        default="outputs/session31/config_audit.md",
        help="Markdown output path.",
    )
    args = parser.parse_args()

    grouped: dict[str, list[dict[str, str]]] = {}
    all_ok = True
    n_total = 0
    for d in args.configs:
        directory = Path(d)
        rows = audit_dir(directory)
        grouped[str(directory)] = rows
        n_total += len(rows)
        for r in rows:
            status = "ok" if r.get("_ok") == "true" else "FAIL"
            if r.get("_ok") != "true":
                all_ok = False
            print(f"  [{status}] {directory.name}/{r['Model']}")

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(render_markdown(grouped))
    print(f"all_ok={all_ok}; {n_total} configs; wrote {out_path}")
    if not all_ok:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
