"""Latent-drift mechanism: how far the markov ROLLOUT strays from the true encoded
latent vs horizon. Relative drift = mean_i ||z_markov[i, impact+H] - z_dns[i, impact+H]||
/ ||z_dns[i, impact+H]|| over test_b. Scale-invariant, so it compares across families.
Uses the rollouts generated by session27_gen_rollouts_uncond + the production refs.
"""
from __future__ import annotations

from pathlib import Path

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

REPO = Path(__file__).resolve().parents[1]
PROD = REPO / "outputs/session18/exp_b1_test3"
SPLIT = "test_b"
HZ = [1, 2, 4, 8, 12, 16, 20, 24]
FAMILIES = [
    ("tf-no-c", REPO / f"outputs/session27/rollouts_noc_tf/{SPLIT}.npz", "#C0520F", "-"),
    ("lstm-no-c", REPO / f"outputs/session27/rollouts_noc_lstm/{SPLIT}.npz", "#E08A4A", "-"),
    ("JEPA (cond, prod)", PROD / f"rollouts_jepa_d64_test1_noBN/{SPLIT}.npz", "#2E7D4F", "--"),
    ("Fukami AE", PROD / f"rollouts_fukami_d64_noBN/{SPLIT}.npz", "#3C6FB0", ":"),
]


def main():
    fig, ax = plt.subplots(figsize=(5.2, 3.3))
    print("=== relative rollout drift ||z_markov-z_dns||/||z_dns|| (test_b, median) ===")
    for name, npz, col, ls in FAMILIES:
        if not npz.exists():
            print(f"  {name}: MISSING {npz}"); continue
        b = np.load(npz, allow_pickle=True)
        zd = b["z_dns"].astype(np.float64); zm = b["z_markov"].astype(np.float64)
        impact = b["impact_frame"].astype(int)
        med = []
        for H in HZ:
            d = []
            for i in range(zd.shape[0]):
                te = impact[i] + H
                if te >= zd.shape[1]:
                    continue
                num = np.linalg.norm(zm[i, te] - zd[i, te]); den = np.linalg.norm(zd[i, te])
                d.append(num / max(den, 1e-9))
            med.append(np.median(d))
        ax.plot(HZ, med, ls, color=col, lw=1.9, label=name)
        print(f"  {name:18s} " + "  ".join(f"H{H}:{m:.2f}" for H, m in zip(HZ, med)), flush=True)
    ax.set_xlabel("forecast horizon H (frames after impact)")
    ax.set_ylabel("relative rollout drift\n||z_markov - z_dns|| / ||z_dns||")
    ax.set_title("Latent drift of the markov rollout (test_b)", fontsize=9)
    ax.legend(fontsize=7); ax.grid(alpha=0.25)
    fig.tight_layout()
    out = REPO / "outputs/session27/drift_uncond.pdf"
    fig.savefig(out, bbox_inches="tight"); print(f"\n[drift] figure -> {out}")


if __name__ == "__main__":
    main()
