"""Assemble the Session 31 ROM eval (Q1/Q2/Q3) into numbers.json + macros.

Mirrors the Session 28 provenance harness: the three ROM payloads
(``q1_representation.json``, ``q2_temporal.json``, ``q3_pressure.json``) are
reduced to the headline cells, an optional case-clustered bootstrap CI dump is
overlaid, the merged ledger is validated (no duplicate names/macros, required
``value``) and written to ``outputs/session31/numbers.json``, and the LaTeX macros
are rendered to ``paper/macros_session31.tex``. No numeric literal ever reaches a
``.tex`` source: the manuscript reads these ``\\providecommand`` macros only.

Usage:
    python scripts/session31/assemble_report.py            # merge + emit
    python scripts/session31/assemble_report.py --check    # validate only, no write
"""

from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from src.evaluation.report_session31 import (  # noqa: E402
    apply_cis,
    build_headline_records,
    emit_macros,
    merge_and_validate,
)

REPO = Path(__file__).resolve().parents[2]
Q1 = REPO / "outputs" / "session31" / "q1_representation.json"
Q2 = REPO / "outputs" / "session31" / "q2_temporal.json"
Q3 = REPO / "outputs" / "session31" / "q3_pressure.json"
CI_DUMP = REPO / "outputs" / "session31" / "ci_dump.json"
OUT_NUMBERS = REPO / "outputs" / "session31" / "numbers.json"
OUT_MACROS = REPO / "paper" / "macros_session31.tex"


def _sha256(path: Path) -> str | None:
    if not path.exists():
        return None
    h = hashlib.sha256()
    h.update(path.read_bytes())
    return h.hexdigest()


def _git_commit() -> str:
    out = subprocess.run(["git", "rev-parse", "HEAD"], cwd=REPO, capture_output=True, text=True)
    return out.stdout.strip() if out.returncode == 0 else "UNKNOWN"


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--check", action="store_true", help="Validate only; do not write.")
    p.add_argument("--window", default="windowed", choices=("windowed", "all_frames"))
    p.add_argument("--ci-dump", default=str(CI_DUMP))
    p.add_argument("--numbers-out", default=str(OUT_NUMBERS))
    p.add_argument("--macros-out", default=str(OUT_MACROS))
    args = p.parse_args(argv)

    q1 = json.loads(Q1.read_text())
    q2 = json.loads(Q2.read_text())
    q3 = json.loads(Q3.read_text())

    records = build_headline_records(q1, q2, q3, window=args.window)

    ci_path = Path(args.ci_dump)
    ci_meta = {
        "applied": False,
        "path": str(ci_path.relative_to(REPO)) if ci_path.exists() else None,
    }
    if ci_path.exists():
        ci_blob = json.loads(ci_path.read_text())
        ci_numbers = ci_blob.get("numbers", ci_blob)
        records = apply_cis(records, ci_numbers)
        ci_meta = {
            "applied": True,
            "path": str(ci_path.relative_to(REPO)),
            "n_boot": ci_blob.get("n_boot"),
            "sha256": _sha256(ci_path),
        }

    numbers = merge_and_validate([{"numbers": records}])
    n_ci = sum(1 for r in numbers.values() if r.get("ci_low") is not None)
    print(
        f"[assemble] {len(numbers)} numbers, {n_ci} with CIs "
        f"(window={args.window}, ci_dump {'applied' if ci_meta['applied'] else 'absent'})"
    )
    if args.check:
        print("[assemble] check mode: not writing")
        return 0

    provenance = {
        "generated_iso": datetime.now(timezone.utc).isoformat(),
        "git_commit": _git_commit(),
        "window": args.window,
        "sources": {
            "q1": {"path": str(Q1.relative_to(REPO)), "sha256": _sha256(Q1)},
            "q2": {"path": str(Q2.relative_to(REPO)), "sha256": _sha256(Q2)},
            "q3": {"path": str(Q3.relative_to(REPO)), "sha256": _sha256(Q3)},
        },
        "ci_dump": ci_meta,
        "n_numbers": len(numbers),
        "n_with_ci": n_ci,
    }
    payload = {"_provenance": provenance, "numbers": numbers}
    OUT = Path(args.numbers_out)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(payload, indent=2, sort_keys=True))
    print(f"[assemble] wrote {OUT}")

    header = [
        "% AUTO-GENERATED by scripts/session31/assemble_report.py. DO NOT EDIT.",
        f"% source: {OUT.relative_to(REPO)}",
        f"% generated: {provenance['generated_iso']}",
        f"% provenance commit: {provenance['git_commit']}",
        f"% CIs: case-clustered bootstrap over Test B cases ({n_ci}/{len(numbers)} cells)",
    ]
    macros = emit_macros(numbers, header=header)
    MAC = Path(args.macros_out)
    MAC.parent.mkdir(parents=True, exist_ok=True)
    MAC.write_text(macros)
    n_macro_lines = macros.count("\\providecommand")
    print(f"[assemble] wrote {MAC} ({n_macro_lines} macros)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
