"""Session 31 Track F: the canonical ROM comparison table (LaTeX, macros only).

Emits ``outputs/session31/tables/rom_comparison.tex`` -- a ``booktabs`` table whose
every numeric cell is a ``\\providecommand`` macro from ``macros_session31.tex`` (no
numeric literal). One row per canonical model; the columns span the three ROM
questions (Q1 representation / decode floor, Q2 forecast, Q3 pressure inference).
Cells whose number carries a case-clustered bootstrap CI in
``outputs/session31/numbers.json`` render the CI as a small ``[lo, hi]`` companion
using the ``lo``/``hi`` macros; cells without a CI render the point only.

    python scripts/session31/make_table.py
    python scripts/session31/make_table.py --standalone   # also build a compile check
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from src.evaluation.report_session31 import (  # noqa: E402
    CANONICAL_MODELS,
    MODEL_LABEL,
    name_and_macro,
)

REPO = Path(__file__).resolve().parents[2]
NUMBERS = REPO / "outputs" / "session31" / "numbers.json"
OUT_DIR = REPO / "outputs" / "session31" / "tables"

# (header, arrow, kind, extra-kwargs) for each numeric column, in table order.
COLUMNS = [
    (r"decode floor VRMSE $\downarrow$", "repr_floor_vrmse", {}),
    (r"floor SSIM $\uparrow$", "repr_floor_ssim", {}),
    (r"$R^2(C_L)$ $\uparrow$", "repr_mlp", {"target": "C_L"}),
    (r"$R^2(\Omega_w)$ $\uparrow$", "repr_mlp", {"target": "wake_enstrophy"}),
    (r"field VRMSE$_{h=8}$ $\downarrow$", "fore_field", {"which": "model", "h": 8}),
    (r"closure $\bar{R}^2_{h=8}$ $\uparrow$", "fore_merit", {"h": 8}),
    (r"press$\to$obs $\bar{R}^2$ $\uparrow$", "pres_obs_mean", {}),
    (r"press$\to$field VRMSE $\downarrow$", "pres_field_vrmse", {}),
]


def _cell(model: str, kind: str, kwargs: dict, has_ci: dict[str, bool]) -> str:
    name, macro = name_and_macro(kind, model, **kwargs)
    if has_ci.get(name):
        return f"$\\{macro}$ {{\\scriptsize$[\\{macro}lo,\\,\\{macro}hi]$}}"
    return f"$\\{macro}$"


def build_table(numbers: dict) -> str:
    has_ci = {n: (r.get("ci_low") is not None) for n, r in numbers.items()}
    n_ci = sum(has_ci.values())
    headers = " & ".join(["model"] + [c[0] for c in COLUMNS])
    lines = [
        "% AUTO-GENERATED by scripts/session31/make_table.py. DO NOT EDIT.",
        "% Requires \\input{macros_session31.tex} (values + [lo,hi] CI macros).",
        "% Every numeric cell is a macro; no literal appears here.",
        "\\begin{table}",
        "\\centering",
        "\\caption{Reduced-order-model comparison across the six canonical encoders "
        "(v2.2, Test B, in-window). Q1 decode floor and representation probes, Q2 "
        "matched-predictor forecast field VRMSE and observable closure at $h=8$, and "
        "Q3 wall-pressure state inference. Bracketed ranges are 2.5--97.5\\% "
        "case-clustered bootstrap CIs over the ten Test B cases "
        f"($B=1000$; {n_ci} cells carry a CI). VRMSE lower is better; $R^2$ and SSIM "
        "higher is better.}",
        "\\label{tab:rom_comparison}",
        "\\footnotesize",
        "\\setlength{\\tabcolsep}{4pt}",
        "\\begin{tabular}{l" + "c" * len(COLUMNS) + "}",
        "\\toprule",
        headers + " \\\\",
        "\\midrule",
    ]
    for model in CANONICAL_MODELS:
        cells = [MODEL_LABEL[model]] + [
            _cell(model, kind, kwargs, has_ci) for (_h, kind, kwargs) in COLUMNS
        ]
        lines.append(" & ".join(cells) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]
    return "\n".join(lines)


def _standalone_wrapper(table_rel: str) -> str:
    return "\n".join(
        [
            "\\documentclass[11pt]{article}",
            "\\usepackage{booktabs,amsmath,amssymb}",
            "\\usepackage[margin=1in,landscape]{geometry}",
            "\\input{../../../paper/macros_session31.tex}",
            "\\begin{document}",
            "\\pagestyle{empty}",
            f"\\input{{{table_rel}}}",
            "\\end{document}",
            "",
        ]
    )


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--numbers", default=str(NUMBERS))
    p.add_argument("--out-dir", default=str(OUT_DIR))
    p.add_argument("--standalone", action="store_true", help="Also build a pdflatex check.")
    args = p.parse_args(argv)

    numbers = json.loads(Path(args.numbers).read_text())["numbers"]
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    table = build_table(numbers)
    table_path = out_dir / "rom_comparison.tex"
    table_path.write_text(table)
    print(f"[table] wrote {table_path}")

    if args.standalone:
        wrap = out_dir / "rom_comparison_standalone.tex"
        wrap.write_text(_standalone_wrapper("rom_comparison.tex"))
        proc = subprocess.run(
            ["latexmk", "-pdf", "-interaction=nonstopmode", "-halt-on-error", wrap.name],
            cwd=out_dir,
            capture_output=True,
            text=True,
        )
        pdf = out_dir / "rom_comparison_standalone.pdf"
        if proc.returncode == 0 and pdf.exists():
            print(f"[table] standalone compiled OK -> {pdf}")
        else:
            tail = "\n".join(proc.stdout.splitlines()[-25:])
            print(f"[table] standalone compile FAILED (rc={proc.returncode}):\n{tail}")
            return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
